name = "elders-pvp"
main = "src/index.js"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "Lobby" }
]

[[migrations]]
tag = "v1"
new_classes = ["Lobby"]
